name: Go CI

on:
  push:
    branches: [ "main", "work" ]
  pull_request:
    branches: [ "main", "work" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Format
      run: gofmt -w main.go main_test.go && git diff --exit-code
    - name: Vet
      run: go vet ./...
    - name: Test
      run: go test ./...
    - name: Build
      run: go build ./...
